# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50c6fe540db03a9a3141ab22f60fd9b4fb7e5244a5697337067317c63af5782d9f5c716abdb167f00160b14e1aec068d287653cd0fedbcd138e21eb275aec3cc

test:
  secret_key_base: 98e7eee565ca0a6aab8ce0171e8e5d4e2994e4600f8bdb18d552d161dd069887f49d63a6e0796c01cb39c8c2b3c167dc5a731f5b060c79d225099990b0ea18b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
